var bitcoin = double.Parse(Console.ReadLine());
var yuan = double.Parse(Console.ReadLine());
var com = double.Parse(Console.ReadLine());
var lev = bitcoin * 1168;
var dolar = yuan * 0.15;
var dolar1 = dolar * 1.76;
var alllev = lev + dolar1;
var euro = alllev / 1.95;
var commision = euro *( com / 100);
Console.WriteLine(Math.Round(euro-commision, 2));
